### PR TITLE
Running on node 6 (solves issue #6)

### PR DESCRIPTION
**Pull request by xuv**
Mainly did some package updates to get it working. 
And added config file/options here and there.

### CODE REVIEW

**Comment by hanbyul-here** [comment]
This is awesome. Thank you so much @xuv  !!!!!

**Comment by xuv** [comment]
:) Glad you like it. I mainly did it also for myself. :) Actually, I can now work on the feature I'd like to add. :)

**Comment by hanbyul-here** [comment]
I am very excited to see what you are making :) ! I will give you commit access in case you feel need to do more !

**Comment by xuv** [comment]
Wow. Thanks for the commit access. :)
My main goal is to be able to 3D print multiple tiles and have them stitch together (not virtually, but once printed). So for that, I was thinking of having some border buildings create a hole in the tile instead of being added. I think that if the center of a border building is outside the tile, it should be removed and make a dent in the mesh. If its center is inside the tile area, it can be added and stick out like it does now. That way, tiles should be able to be stitched together. I need to test this, of course. There may also need to be some clearance between the two parts to take into account. Not sure. Anyway. Here is a print I did. :) https://www.instagram.com/p/BIoAcSOAxPh/?taken-by=xuv.be

**Comment by hanbyul-here** [comment]
I love yellow green look of the tile:) ! 

This might not be related to your interest directly, but in case this info helps you: I was not sure how to stitch the tiles (virtually, so it can be spitted as a big tile) because of the buildings laying on the borders. But based on [my coworker's project](https://github.com/karimnaaji/vectiler), it seems overwrapping buildings are not really a problem; I probably can just bundle everything including overwrapping buildings then export it to obj. I didn't try this yet so it is only hypothetically possible right now.   💭  

Your plan sounds very cool, it will be like a big puzzle! Please let me know when you make progress!

**Comment by xuv** [comment]
@hanbyul-here Thx. Have started digging in the code and testing things. I have looked at vectiler before, hoping it was going to solve my problem. But actually not. I'm interested in making a physical puzzle. Indeed in a virtual world, buildings don't mind collapsing into each other. :) But once 3d printed...
Anyway, found the necessary bits I need, I think. But won't have time in the coming weeks. Hoping to be back at it in September. I'll let you know of the advancement. I need to do it. I already bought the filament, so... no turning back :)

**Pull request merged**
